### ISSUE TITLE
[QA] Backpack Equip/Unequip Exception & Profile Save Failure

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#2382] opened 2024-10-09 16:01 UTC
### **Explorer Alpha build versions:**

- **v0.33.0**

### **Issue Description:**
When equipping or unequipping a wearable item in the backpack, if the backpack is closed before the wearable appears in the character preview, an exception is thrown. This prevents the changes from being saved to the user's profile. Initially, this issue was reproducible, but it seems to have become intermittent.

Additionally, writing to the profile fails without a retry mechanism or feedback to the player. This results in players being unaware that their changes to the profile have not been saved.

### **STR:** 

1. Open the backpack.
2. Equip or unequip a wearable item.
3. Close the backpack before the wearable appears in the character preview.
4. Observe the thrown exception and the inability to save changes.

**Expected Behavior:**
- The wearable should appear in the character preview and the changes should save to the profile without errors.
- Players should receive a notification or message if saving to the profile fails.

**Actual Behavior:**
- An exception is thrown when the backpack is closed prematurely.
- Changes to the profile do not save, and players are not notified of the failure.

https://github.com/user-attachments/assets/e2fcb888-e47d-4f47-91cf-ebb1e39268f7

[Fran Backpack Exception Issue.txt](https://github.com/user-attachments/files/17311267/Fran.Backpack.Exception.Issue.txt)

**Comment by davidejensen** [comment] 2024-10-14 09:22
I was investigating this, the actual problem is more specific, the first time it's working fine, by waiting a moment it would show the updated avatar and would save the changes, the problem is the actual second request, that it's performed very fast close to the first one.
It is failing because the backend is still processing the first request and we cannot do much about it, this doesn't break the flow as the next time you change something it will work fine, hence I would close this as it's not controllable on our side.
What do you think @m3taphysics ?

**Comment by m3taphysics** [comment] 2024-10-14 09:29
Does not break flow downgraded to a medium, we are discussing a retry mechanism for when the profile cannot be deployed and it is because of an on-going deployment.

**Closed** 2024-10-17 11:43 UTC
Labels: bug, 2-medium
