### ISSUE TITLE
[QA] Beaming up: when getting to the sky platform, avatar falls from very high 

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1243] opened 2024-06-12 20:10 UTC
### **Explorer Alpha build version:**

[0.3.477-g5ad20358-main]

### **Issue Description:**

Beaming up: when getting to the sky platform, avatar falls from very high:

![image](https://github.com/decentraland/unity-explorer/assets/146749313/13166dad-62a5-47e0-9465-9db1685757cd)

It seems the avatar falls from a higher point in Alpha compared to Unity renderer. 

**Unity renderer:**

https://github.com/decentraland/unity-explorer/assets/146749313/3c94d825-36e1-4b97-862b-063f13c405bb

**Alpha:**

https://github.com/decentraland/unity-explorer/assets/146749313/3a5cd142-70df-4d9a-be7b-30bbe00f70a2

The Alpha video has a lot of delay and doesn't really show how high the point is. 

Is the action of falling from a high point the expected/ desired behavior after doing the "Beaming up" ? 

### **Steps to reproduce:**

  1. Go to the bar
  2.Try to beam up to the sky platform
  

### **Expected behaviour:**
Animation could be a different one

### **Current behaviour:**
Avatar falls from a high height

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [x ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ] Medium
- [ x] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by m3taphysics** [comment] 2024-06-13 10:32
@LucasLioyQA is this a bug with the avatar spawn height? Is it the same in Unity-Renderer. If the spawn positions are different we should bug it so that we fix the spawn height when going up the teleport.

Please also add a video :)

**Comment by LucasLioyQA** [comment] 2024-06-13 14:35
@m3taphysics  Is the action of falling from a high point the expected/ desired behavior after doing the "Beaming up" ?  It seems the avatar falls from a higher point in Alpha compared to Unity renderer.

I have included videos on this ticket's description (sorry for the quality, there is a lot of delay in both, especially in Alpha, and it doesn't really show the height)

**Comment by anicalbano** [comment] 2024-07-04 17:48
The spawn height is the same in alpha as it is on render. Closing the ticket since it´s not a bug.

**Closed by anicalbano** 2024-07-04 17:48 UTC
Labels: bug, 2-medium
