### ISSUE TITLE
[QA] Horizontal character on the floor

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2116] opened 2024-09-20 15:02 UTC
### **Explorer Alpha build versions:**
0.28.40

### **Issue Description:**
When using a specific emote, in the last frames ends up putting the avatar in that position for some reason, and then that position is kept forever (except while playing other emotes)

### **STR:** 

  1. Open 0.28.40
  2. Use X emote (emote that will be confirmed later today just in case)
  3. Validate that after that emote you will appear on the floor for other players than you.

### **Expected behavior:**
No emote should end up leaving the avatar on the floor 

### **Current behavior:**
When using a specific emote, in the last frames ends up putting the avatar in that position for some reason, and then that position is kept forever (except while playing other emotes)

#### **Evidence:**

https://github.com/user-attachments/assets/5234bcab-06fc-467b-b6de-fac8b69a869e

#### **Additional Notes:**
Tested on Macos M1 
Tested on Windows 11Pro

**Comment by pravusjif** [comment] 2024-09-23 09:47
This emote puts the avatar in an incorrect rotation by the end of its animation, and it can't be correcte without restarting the application: https://decentraland.org/marketplace/contracts/0x75d3148cf3289550af3936ecd4f154c8c6c18329/tokens/105312291668557186697918027683670432318895095400549111254310977542

Sometimes the avatar is left rotated almost 90 degrees and that's why it looks like it's lying on the floor, other times it just rotatets a little "the UP vector of the avatar"

**Comment by QThund** [comment] 2024-09-24 10:14
This is what I see in the marketplace:
![Image](https://github.com/user-attachments/assets/4a6851d9-f155-4e22-8c17-59dd47a164f2)

But I can't reproduce it in DCL:
https://github.com/user-attachments/assets/9190e919-1721-4cf3-8f1e-be9a5688b21e

**Comment by QThund** [comment] 2024-09-24 14:33
Ok I'm able to reproduce it now.

**Comment by QThund** [comment] 2024-09-25 13:22
The only thing that fixes the problem is adding a keyframe to all main animations (idle, walk, jog, run, start_jump, etc.) that sets rotation to (90º, 0º, 0º). Trying to set the rotation values manually is useless as the animator will override it when blending the emote animation with the other animations.
And the animation that is causing the problem should be fixed too, it does not make sense that it rotates the Armature by (0º, -129.874º, 0º).

**Comment by m3taphysics** [comment] 2024-09-27 08:46
I have spoken to @Kaze-No-Kai to help fix this with the curators.

**Closed by m3taphysics** 2024-09-27 08:46 UTC
Labels: bug, 1-high
