### ISSUE TITLE
Bound LOD radius to quality settings

### ISSUE THREAD

**Issue by olavra** [decentraland/unity-explorer#979] opened 2024-05-07 00:04 UTC
Currently, the configuration of LOD0, LOD1 levels is hardcoded. In the debug menu it can be changed, but only the LOD1 threshold. 
Also, LOD0 is never used for SDK scenes.
The behaviour should be similar as the following:
- Change the concept of LOD thresholds to LOD radius
- Add the concept of SDK Scene radius
- LOD 1 radius does not need to be defined as it goes as far as the scene load radius allows. 
- Radius determine the number of parcels of distance from the previous LOD level. 
- Values are bound to quality settings, and different per quality.

As an example, if we define:
SDK Radius: 3
LOD0 Radius: 6
It will mean that from 0 to 3, it will load SDK scenes or LOD0 in the case of SDK6
From 4 to 6, it will load LOD0
From 7 to Scene load radius, will load LOD1

Quality settings values:
**High**
- SDK scene radius: 3
- LOD0 radius: 10
- Scene Load Radius: 100

**Medium**
- SDK: 2
- LOD0: 4
- Scene Load Radius: 50

**Low**
- SDK: 1
- LOD0: 2
- Scene Load Radius: 20

On debug menu, instead of showing LOD threshold, we will have the following parameters
- SDK radius
- LOD0 radius
- Scene Load Radius

**Comment by m3taphysics** [comment] 2024-05-08 13:59
Similar/Duplicate of #446

**Closed** 2024-10-02 13:01 UTC
Labels: suggestion, 2-medium
