### ISSUE TITLE
[QA] Name Displayed in First-Person View in 'Metadyne Labs'

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#958] opened 2024-05-06 13:01 UTC
### **Explorer Alpha build version:**
0.3.335-g8f637032-main

### **Issue Description:**
In the 'Metadyne Labs' world, when the user enters first-person view and looks up with the camera, their name display is visible. However, in production environments, when the user enters a scene that forces first-person view, their name display is not visible when looking up.

### **Steps to reproduce:**

1. Enter the 'Metadyne Labs' world.
2. Look up with the camera.

### **Expected behaviour:**
In production environments, the user's name display should not be visible when looking up in first-person view.

### **Current behaviour:**
In the 'Metadyne Labs' world, the user's name display is visible when looking up in first-person view.

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [ ❌ ]  100%

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [❌ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [ ❌] Medium
- [ ] Low

### **Platforms / OS:**
- [❌ ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Evidence:**
![metadyneL01](https://github.com/decentraland/unity-explorer/assets/146741383/629f464f-1c38-40ce-afe1-0a01c0b40eda)

PROD:
![Screenshot at May 06 09-58-17](https://github.com/decentraland/unity-explorer/assets/146741383/0c68ea1a-04a2-40bc-b452-affa959683b7)

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H   2.30 GHz

**Comment by olavra** [comment] 2024-05-06 21:26
This is a duplicate of #733

**Closed by olavra** 2024-05-06 21:26 UTC
Labels: bug, 2-medium, new, ui
