### ISSUE TITLE
[QA] Text spills out of the button when getting the ball in the basketball game

### ISSUE THREAD

**Issue by LucasLioyQA** [decentraland/unity-explorer#1245] opened 2024-06-12 20:25 UTC
### **Explorer Alpha build version:**

[0.3.477-g5ad20358-main]

### **Issue Description:**
Text spills out of the button when getting the ball in the basketball game:

![image](https://github.com/decentraland/unity-explorer/assets/146749313/8f966890-1702-4688-87b3-2c8393261fb4)

Notice how in regular explorer it is ok: 

![image](https://github.com/decentraland/unity-explorer/assets/146749313/a2d562e6-501c-4a5c-9813-63a8aa109b9f)

### **Steps to reproduce:**

  1.Go to the basketball game
  2. Get the ball
 

### **Expected behaviour:**
Text shouldn't spill out of the box

### **Current behaviour:**
Text spills out of the box

### **Reproduction rate:**
- [ ] < 10%
- [ ]  < = 25%
- [ ]  50%
- [ ]  < = 75%
- [x ]  100%

### **Severity:**

- [ ] Cosmetic
- [x ] Minor
- [ ] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x ] Medium
- [ ] Low

### **Platforms / OS:**
- [x ] Windows 11
- [ ] Windows 10
- [ ] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

**Comment by aixaCode** [comment] 2024-06-13 10:35
@LucasLioyQA Is the behaviour different in unity-renderer?

**Comment by LucasLioyQA** [comment] 2024-06-13 13:29
@aixaCode It seems ok there:  (I have added this to the ticket's description now) 

![image](https://github.com/decentraland/unity-explorer/assets/146749313/f0b58a0b-d2f0-4201-bad5-5f6229667bec)

**Comment by sandrade-dcl** [comment] 2024-07-30 13:38
Comparing both explorers (the old one and E@), if we set the same size of the screen, the UI looks identical, so it's not a bug. What is happening is that, depending on the resolution of the window, the text of the UI could appears out of the box or not, but this is not a problem of the Explorer but of how the UI is created in the scene's code.

### OLD EXPLORER
![Image](https://github.com/user-attachments/assets/b0c24fd8-6aa4-494c-ad7f-4d21bd8507e9)

### EXPLORER ALPHA
![Image](https://github.com/user-attachments/assets/a774ed0e-3901-47f0-8c76-72bc276554ce)

@anicalbano could you please re-check it and close it? Thanks!

**Comment by anicalbano** [comment] 2024-07-31 11:30
Can confirm! It's the same in prod and Alpha. I'll close the ticket.

**Closed by anicalbano** 2024-07-31 11:30 UTC
Labels: bug, 3-low
