### ISSUE TITLE
[QA] Avatars are able to run through objects and scenes 

### ISSUE THREAD

**Issue by DafGreco** [decentraland/unity-explorer#2404] opened 2024-10-11 13:14 UTC
### **Explorer Alpha build versions:**
0.34.0

### **Issue Description:**
Due to a current issue with colliders, users are able to run through objects like sculptures or scenes like the NFT museum

### **STR:** 

  1. Open 0.34.0
  2. Teleport multiple times to Genesis Plaza 
  3. Go to the NFT museum on Genesis plaza 
  4. Validate that there are no colliders when teleporting multiple times to Genesis Plaza 

### **Expected behavior:**
Colliders should work properly after teleporting to certain places 

### **Current behavior:**
Due to a current issue with colliders, users are able to run through objects like sculptures or scenes like the NFT museum

#### **Evidence:**

https://github.com/user-attachments/assets/363ce33f-76f6-414b-9efd-cdc2d2da2e4b

#### **Additional Notes:**
Able to reproduce it on Windows 11 pro 
16 GB RAM

**Comment by m3taphysics** [comment] 2024-10-31 12:26
Duplicate of: https://github.com/decentraland/unity-explorer/issues/2608

**Closed by m3taphysics** 2024-10-31 12:26 UTC
Labels: bug, 2-medium
