### ISSUE TITLE
[QA] "Sum a Terra" skin not loading in backpack

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1839] opened 2024-08-20 15:11 UTC
### **Explorer Alpha build versions:**

- **v0.21.0**

### **Issue Description:**
The "Sum a Terra" skin does not load correctly in the backpack preview. This issue prevents the skin from being visible or properly displayed in the backpack view.

**WEARABLE URN:** 
https://decentraland.org/marketplace/contracts/0xbf65a0f5a6115ca5cd1ec9c13c993d412eaa009c/items/0

#### **USER LOGS:**
https://drive.google.com/file/d/16SGzGSpH4GvFp_Uy0m4A44a6ZQqIWFuf/view
### **STR:** 

1. Launch the explorer.
2. Open the backpack preview.Equip the "Sum a Terra" skin.
3. Equip the "Sum a Terra" skin.

### **Expected behavior:**
![sum a Terra-Prod](https://github.com/user-attachments/assets/34c54391-cd87-4b84-8e4c-98cd5b935301)

### **Current behavior:**
![image](https://github.com/user-attachments/assets/43857d13-f58b-43a3-b0ca-ffcd3c42b9b5)

**Comment by olavra** [comment] 2024-08-21 10:53
Apparently its displaying the legs and it shouldnt. This may be a duplicate of #1770

**Comment by lorux0** [comment] 2024-08-23 18:38
It is showing it correctly on my end:

![Image](https://github.com/user-attachments/assets/28e2c14a-f7d9-407b-9421-fb9ff6022245)

**Closed as completed** 2024-08-26 13:30 UTC
Labels: bug, 2-medium
