### ISSUE TITLE
[QA] Mac | Application Crashes or Stuck at Loading Screen When Teleporting to Meta GamiMall

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1283] opened 2024-06-19 18:29 UTC
### **Explorer Alpha build version:**
v.04.0

### **Issue Description:**
When attempting to teleport to the Meta GamiMall scene at coordinates (145, 60), the application either crashes or gets stuck at the loading screen at 60%, eventually returning the user to the starting scene without teleporting. After multiple attempts (at least 6), the scene finally loads successfully.

### **Steps to reproduce:**

1. Launch the Explorer
2. Use the teleport command to go to Meta GamiMall at coordinates (145, 60).

### **Expected behavior:**
The user should be able to teleport to the Meta GamiMall scene at coordinates (145, 60) without the application crashing or getting stuck at the loading screen.

### **Current behavior:**
**[LOGS](https://github.com/user-attachments/files/15904709/Explorer-2024-06-19-144751.ips.zip)**
https://github.com/decentraland/unity-explorer/assets/146741383/84441408-9ee9-45da-939c-3a3d6793f114

### **Platforms / OS:**
- [ ] Windows 11
- [ ] Windows 10
- [❌] Mac Sonoma
- [ ] Mac (specify the version on Additional Notes)

#### **Additional Notes:**
Macbook M1 Pro Sonoma 14.5

**Comment by mikhail-dcl** [comment] 2024-06-20 11:08
it's duplicate of https://github.com/decentraland/unity-explorer/issues/1236

**Closed by mikhail-dcl** 2024-06-20 11:08 UTC
Labels: bug, 0-critical, new, mac
