### ISSUE TITLE
[QA] Meta Gami Mall - Summon Shuttle Pad Issue

### ISSUE THREAD

**Issue by Ludmilafantaniella** [decentraland/unity-explorer#1959] opened 2024-09-02 19:37 UTC
### **Explorer Alpha build versions:**

- **v0.25.0**

### **Issue Description:**
In the 'Meta Gami Mall' scene at coordinates (145,60), the 'Summon Shuttle pad' is not functioning correctly. When the button is pressed, the player is spawned outside the platform instead of being correctly positioned on it.

### **STR:** 

1. Launch the explorer and teleport to 'Meta Gami Mall' (145,60).
2. Attempt to use the 'Summon Shuttle pad' by pressing the button.
3. Observe where the player is spawned.

### **Expected behavior:**
- The player should be spawned on the platform when using the 'Summon Shuttle pad'.

https://github.com/user-attachments/assets/864ec508-9722-4fcf-92c0-d1b506389f6d

### **Current behavior:**
- The player is spawned outside the platform instead of on the 'Summon Shuttle pad'.

https://github.com/user-attachments/assets/8d9bebc2-d158-4498-8fa0-80f7443229a7

#### **Additional Notes:**
Windows 11. 12th Gen Intel(R) Core(TM) i7-12650H 2.30 GHz. nvidia geforce RTX
Macbook M1 Pro Sonoma 14.5

**Comment by Kaze-No-Kai** [comment] 2024-11-14 10:19
Hi team, if we can update the priority and look into this issue after the fest if we have the capacity as it is one of the popular scenes and users still use web to access it because of the bug above. Thanks in advance

**Comment by QThund** [comment] 2024-11-27 21:42
Some info:
-The scene is working properly in the old explorer.
-The object of the moving platform, called Pad.001, is moved by an Animator in its parent.
-The animator is being disabled as soon as it is enabled, canceling the animation.
-If you quickly enable the animator the animation works fine.
-The reason why the animator is disabled seems to be that the character is not on the platform.
-The character is not on the platform because it is not being properly teleported there.
-A timeout occurs when teleporting the character (it takes 30 seconds since you push the button and the exception appears). This exception is thrown at the TeleportCharacterSystem.TeleportPlayer method, when the TeleportCharacterIntent.Timeout returns true.

**Comment by QThund** [comment] 2024-11-28 12:46
The situation has changed after this PR was merged, the timeout has been fixed but the position is still wrong.
https://github.com/decentraland/unity-explorer/pull/2901

**Comment by QThund** [comment] 2024-11-28 13:09
Now the character teleports to the right place (2350, 985) but it's moved upwards after that.

**Comment by QThund** [comment] 2024-11-28 13:51
The wrong Y value is coming from RestrictedActionsAPIWrapper.MovePlayerTo. Which means that it comes from the scene code.

**Comment by wacaine** [comment] 2024-12-04 04:27
@QThund  thanks for the analysis and patching.   I remain unclear on one part.   If it works in old explorer and you fixed the issue in new explorer why does it continue to not work?   Is there some difference in functionality in the new client that is working as expected however differently than old explorer to make the pad not work....Just a guess.  The old explorer teleport seems to "happen faster".  They teleport and fall to ground faster.   The new explorer the teleport fall appears to have a delay.   Is that expected functionality for the new client.   I wonder if that introduces enough different for my detect player on pad to not work.  I think we cast for 3.5 meters and if we teleport 8 with a delay in fall it would not detect on pad.  We will try playing with teleport height / ray cast distance

Side question.  Is there a way in the SDK to detect old client vs new?

**Comment by QThund** [comment] 2024-12-05 16:00
Hi @wacaine , the issue is not fixed yet, I'm still investigating. Since I don't have access to the code of the scene it is being like doing reverse engineering or trial and error. My current guess is that the scene needs to detect the avatar on the pad for it to be visible and animated, but for some reason it is not detecting it or it is reacting and hiding too fast, before the avartar touches it, something similar to what you say. I can do a quick test and teleport the avatar at a fixed height.

**Comment by wacaine** [comment] 2024-12-06 02:00
@QThund  full scene here if u want to try directly https://github.com/MetaLiveStudio/MetaGamiMall_GA 

a pruned down version here with me reporting an issue with recurring raycasting. https://github.com/decentraland/sdk/issues/993

**Comment by QThund** [comment] 2024-12-10 14:08
@wacaine I tested the scene locally and everything works fine :/

**Comment by QThund** [comment] 2024-12-12 12:26
@wacaine The last change in the repository was in June, the last time the scene was deployed was in September. Can you please confirm that the scene currently deployed is exactly the same as the scene in the repository?

**Comment by QThund** [comment] 2024-12-12 13:05
I've seen that when I connect to the scene locally it uses a different animation system from what it uses when connecting to the server, and the object hierarchy is different.

**Comment by QThund** [comment] 2024-12-13 12:22
It seems that the behaviour is different when stopping an Animator than when stopping an Animation. The first resets the animation to the beginning, whereas the later just "pauses" the animation. So the platform stays at the same place when the avatar is not on it if we load the version with Animation, but when the version with the Animator is loaded it just moves to its first position and the avatar can't fall onto it.

**Comment by QThund** [comment] 2024-12-13 13:23
```
// Since animation states are now executed through layers, we need to force to 0 if the state is not playing
// otherwise it overrides the current playing state
animator.SetLayerWeight(layerIndex, 0f);
```
By removing this line (151, AnimatorUpdateSystem) the Animator behaves as intended.
For now, we are re-converting the scene using Animations to make it work, and will look for a better solution.

**Comment by QThund** [comment] 2024-12-13 19:39
We re-converted the asset bundles but the proccess has produced the same result (adds Animator component). When converting them locally it produces the intended result (adds Animation component). @dalkia redeployed the AB converter (v33) but it still produces the wrong result.

**Comment by wac84s** [comment] 2024-12-13 21:26
@QThund  thank you for not giving up and keep working this issue.  It sounds like you you found some discrepancy with the Animation system that could be producing the issue.  Let me know if there is anything we can do on our side that works around the problem or just wait and see what you come up with.

**Comment by wacaine** [comment] 2024-12-17 03:20
@QThund  thank you for all your work on this issue.   Is there anything we can do on our end to workaround it?

"For now, we are re-converting the scene using Animations to make it work, and will look for a better solution." - sounds like there might be a workaround SDK side?

**Comment by QThund** [comment] 2024-12-20 19:06
Hi @wacaine , it should be working now, the scene was successfully re-converted. I think we can close this ticket.

**Comment by wacaine** [comment] 2024-12-21 03:43
@QThund  I just tested it works.   The coin sound is not right.   Should be a "mario type coin" sound but its not right.  Sounds find on browser client.

**Closed as completed** 2024-12-29 22:42 UTC
Labels: bug, 1-high
