### ISSUE TITLE
Create a snapshot mechanism

### ISSUE THREAD

**Issue by mikhail-dcl** [decentraland/unity-explorer#21] opened 2023-04-19 09:52 UTC
We need a serialization/snapshot mechanism that will be able to provide the current state of the world. It could be useful for bug analysis, e.g. to complement Sentry reports.
Also we may bisect it further to understand the problems with asset loading such as average loading type, optimization type, etc...
keep in mind that we can serialize Proto components straight away, and with the rest of them Unity Json could come in handy.

**Comment by olavra** [comment] 2024-04-15 09:08
This is a duplicate of #233

**Closed by olavra** 2024-04-15 09:08 UTC
Labels: enhancement, low
